---
title: SiliconSquared LLC
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: At cost hardware within reach
email: info@siliconsquared.com
phone: "+1-123-456-7890"
url: https://avocado.jekyll-themes.com
default-image: "/assets/images/avocado-cover.png"
author:
  name: John Doe
  bio: John is an astronaut. He likes to hang out with his friends when he's not in
    space. He writes his experiences here.
  image: author-image.jpg
  facebook: https://facebook.com
  twitter: https://twitter.com
  quora: https://www.quora.com/
markdown: kramdown
enable-mathjax: true
enable-chartjs: true
permalink: "/blog/:title/"
paginate: 4
paginate_path: "/blog/page:num/"
name: John Doe
projects: I work
include:
- _pages
analytics: UA-92266803-2
tawkto-id: 5cb170e9c1fe2560f3fea30c
share: true
disqus: webjeda-demo
sass:
  sass_dir: "/assets/css/_sass"
  style: compressed
compress_html:
  clippings:
  - html
  - head
  - meta
  - title
  - link
  - body
  - div
  - script
  - header
  - footer
  comments:
  - "<!-- "
  - " -->"
  endings:
  - all
  ignore:
    envs:
    - local
  blanklines: false
  profile: false
  startings: []
destination: _avocado
exclude:
- ".git"
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
